(lecture03:homework)=
# Homework 3

+ Type your name and email in the "Student details" section below.
+ Develop the code and generate the figures you need to solve the problems using this notebook.
+ For the answers that require a mathematical proof or derivation you can either:
    
    - Type the answer using the built-in latex capabilities. In this case, simply export the notebook as a pdf and upload it on gradescope; or
    - You can print the notebook (after you are done with all the code), write your answers by hand, scan, turn your response to a single pdf, and upload on gradescope.

+ The total homework points are 100. Please note that the problems are not weighed equally.

```{note}
+ This is due before the beginning of the next lecture.
+ Please match all the pages corresponding to each of the questions when you submit on gradescope.
```

## Student details

+ **First Name:** Pranav
+ **Last Name:** Kuna
+ **Email:** pkuna@purdue.edu

(lecture03:homework:problem1)=
## Problem 1 - Playing with matrices

Write Python code that constructs the 90-degree rotation matrix in 2D:

$$
A = \begin{bmatrix}
    \cos(\pi/2) &  -\sin(\pi/2) \\
    \sin(\pi/2) & \cos(\pi/2)
\end{bmatrix}
$$

In [68]:
# your code here
import numpy as np
A = np.array([[np.cos(np.pi/2), -np.sin(np.pi/2)], [np.sin(np.pi/2), np.cos(np.pi/2)]])
print(A)

[[ 6.123234e-17 -1.000000e+00]
 [ 1.000000e+00  6.123234e-17]]

Verify that the matrix $A$ rotates the vector $x=\begin{bmatrix} 1 \\ 0 \end{bmatrix}$ by 90 degrees counterclockwise. That is, $A x = \begin{bmatrix} 0 \\ 1 \end{bmatrix}$.

In [69]:
# your code here
A @ np.array([1, 0])

array([6.123234e-17, 1.000000e+00])

Create the matrix:

$$
B = A\cdot A
$$

In [70]:
# your code here
B = A @ A
print(B)

[[-1.0000000e+00 -1.2246468e-16]
 [ 1.2246468e-16 -1.0000000e+00]]

Is $B$ a rotation matrix? What is the effect of $B$ on the vector $x$? Hint: To verify that $B$ is a rotation matrix, you need to check that $B^T\cdot B = I$ (i.e., that $B$ is orthogonal) and that the determinant of $B$ is 1. You can use the ``np.linalg.det()`` function to compute the determinant of a matrix.

In [71]:
# your code here
c = np.linalg.det(B)
print(c)

1.0

Apply the matrix $B$ to the vector $x$ and verify that it rotates the vector by 180 degrees counterclockwise.

In [72]:
# your code here
B @ np.array([1, 0])

array([-1.0000000e+00,  1.2246468e-16])

If you perform 90 degree rotation 4 times, what is the effect of the resulting matrix on the vector $x$? Verify your answer by showing that multiplying $A$ by itself 4 times results in the identity matrix.

In [73]:
# your code here
print(A @ A @ A @ A)

[[ 1.0000000e+00  2.4492936e-16]
 [-2.4492936e-16  1.0000000e+00]]

(lecture03:homework:problem2)=
## Problem 2 - Real data set from high-performance buildings

In this problem you are going to use the `pandas` library to analyze a real dataset collected as part of the NSF-funded project [Sociotechnical Systems to Enable Energy-Aware Residential Communities](https://www.energyawarecommunities.org/).
You can find the raw dataset [here](https://github.com/PurdueMechanicalEngineering/me-239-intro-to-data-science/raw/master/data/temperature_raw.xlsx).

Feel free to download it and open it up in Excel.

### Uploading data files to Google Colab

The first thing we are going to do in this problem is make this file accessible from this notebook. We could simply use the ``download()`` function that I introduced in the lecture. I will put the code at the very last block for your convenience.
However, I still want to show you how you can upload your own data. Here we go.

Go to your Google Drive. We need to select a folder to put the files. To keep things simple, let's just dump everything in "My Drive/Colab Notebooks," i.e., the same folder that contains the copy of this Jupyter notebook which you should have already made  Once you have entered this folder in your Google Drive (just double click on it), drag and drop the `temperature_raw.xlsx` file in there.

Now we need to make the Google Drive visible from this computational session. We do this by mounting the drive. You need to run this code and follow the instructions:

In [74]:
# The following code does not run unless you are running the notebook on Google Colab
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Finally, change directories so that the data files are in the current working directory:

In [75]:
# Only if you are running on Google Colab...
# Print working directory before changing
!pwd
# Change to the desired directory on Google drive
%cd "/content/drive/My Drive/Colab Notebooks"
# Print working directory after changing
!pwd
# List the contents of the directory - Make sure it does contain the files we want:
!ls

/content/drive/My Drive/Colab Notebooks
/content/drive/My Drive/Colab Notebooks
/content/drive/My Drive/Colab Notebooks
temperature_clean.csv  temperature_raw.xlsx  Untitled0.ipynb

Now you should have access to the file and you can **skip the next code block.**
If you tried and something went wrong, simply run the code block below and it will put the data file in the right location for you.

In [76]:
!curl -O https://raw.githubusercontent.com/PurdueMechanicalEngineering/me-239-intro-to-data-science/master/data/temperature_raw.xlsx

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  277k  100  277k    0     0  1971k      0 --:--:-- --:--:-- --:--:-- 1985k

### Loading Excel files

Use the ``pd.read_excel`` function to read the `temperature_raw.xlsx` file.
Name the data frame you read `df`.

In [77]:
import pandas as pd
df = pd.read_excel('temperature_raw.xlsx')

### Questions

Now that you have access to the data frame, let's explore it.
Answer the following questions.

+ Print the first 10 rows of the data frame `df` using the [df.head()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html) method.

In [78]:
# Your code here
df.head(10)

  household        date  score     t_out     t_unit        hvac
0        a1  2018-01-07  100.0  4.283373  66.693229  246.473231
1       a10  2018-01-07  100.0  4.283373  66.356134    5.492116
2       a11  2018-01-07   58.0  4.283373  71.549132  402.094327
3       a12  2018-01-07   64.0  4.283373  73.429514  211.692244
4       a13  2018-01-07  100.0  4.283373  63.923937    0.850536
5       a14  2018-01-07    NaN  4.283373        NaN         NaN
6       a15  2018-01-07    NaN  4.283373        NaN         NaN
7       a16  2018-01-07   56.0  4.283373  66.908970  529.843389
8        a2  2018-01-07   38.0  4.283373  76.063194  556.206108
9        a3  2018-01-07   50.0  4.283373  75.677199  508.592283

+ Print the last 10 rows of the data frame `df` using the [df.tail()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.tail.html) method.

In [79]:
# Your code here
df.tail(10)

     household        date  score      t_out     t_unit       hvac
5640       c41  2020-02-25   84.0  43.642388  70.929066  32.371903
5641       c42  2020-02-25   45.0  43.642388  76.235294   0.000000
5642       c43  2020-02-25   70.0  43.642388  78.302768  15.952602
5643       c44  2020-02-25   59.0  43.642388  76.494637  19.135139
5644       c45  2020-02-25   87.0  43.642388  71.165052  30.794281
5645       c46  2020-02-25    NaN  43.642388        NaN        NaN
5646       c47  2020-02-25   97.0  43.642388  68.603287   5.339391
5647       c48  2020-02-25   92.0  43.642388  73.429239  18.040078
5648       c49  2020-02-25    NaN  43.642388        NaN        NaN
5649       c50  2020-02-25   59.0  43.642388  77.716955  14.405155

+ Print summary statistics of the data set using the [df.describe()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html) method.

In [80]:
# Your code here
df.describe()

             score        t_out       t_unit         hvac
count  4887.000000  5650.000000  4887.000000  4887.000000
mean     74.372826    53.084123    74.172698    81.741860
std      21.643791    19.006199     2.608969    95.901059
min       0.000000     4.283373    63.923937     0.000000
25%      60.000000    37.522495    72.383504    18.321238
50%      79.000000    48.916667    74.178348    51.974687
75%      92.000000    73.079266    76.063591   110.487709
max     100.000000    82.819618    81.941295   693.526701

+ Notice that there is a column called "date", but pandas is not aware that this is actually a date.
Let's make it aware of that using the [pd.to_datetime()](https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html) function.

In [81]:
df.date = pd.to_datetime(df['date'], format='%Y-%m-%d')

+ Count how many NaN values you have on each column. Hint: Use the [df.isna()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isna.html) method to create a boolean array that is True for NaN values and False otherwise. Then, use the [sum()](https://numpy.org/doc/stable/reference/generated/numpy.sum.html) function to count the number of True values. True is equivalent to 1 and False is equivalent to 0.

In [82]:
# your code here
df.isna().sum()

household      0
date           0
score        763
t_out          0
t_unit       763
hvac         763
dtype: int64

+ Clean the data set by dropping all NaN values. Call the cleaned data `df_clean`. Use the [df.dropna()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html) method.

In [83]:
df_clean = df.dropna()

+ Verify that there are no NaN values in `df_clean`.

In [84]:
# your code here
df_clean.isna().sum()

household    0
date         0
score        0
t_out        0
t_unit       0
hvac         0
dtype: int64

+ How many unique households do we have and what are their unique names? Hint: Use the [df.unique()](https://pandas.pydata.org/docs/reference/api/pandas.unique.html) method.

In [85]:
# your code here
r = df_clean.household.unique()
print(r)
len(r)

['a1' 'a10' 'a11' 'a12' 'a13' 'a16' 'a2' 'a3' 'a4' 'a5' 'a6' 'a7' 'a8'
 'a9' 'b17' 'b18' 'b19' 'b20' 'b21' 'b22' 'b23' 'b24' 'b25' 'b26' 'b28'
 'b29' 'b30' 'b31' 'b33' 'c34' 'c35' 'c36' 'c37' 'c38' 'c39' 'c40' 'c41'
 'c42' 'c43' 'c44' 'c45' 'c46' 'c47' 'c48' 'c49' 'c50' 'a15' 'a14' 'b32'
 'b27']

50

+ Print summary statistics for your cleaned dataset.

In [86]:
# your code here
df_clean.describe()

,date,score,t_out,t_unit,hvac
count,4887,4887.000000,4887.000000,4887.000000,4887.000000
mean,2019-01-28 10:29:05.856353536,74.372826,52.907260,74.172698,81.741860
min,2018-01-07 00:00:00,0.000000,4.283373,63.923937,0.000000
25%,2018-07-15 00:00:00,60.000000,37.522495,72.383504,18.321238
50%,2019-01-27 00:00:00,79.000000,48.916667,74.178348,51.974687
75%,2019-08-11 00:00:00,92.000000,73.079266,76.063591,110.487709
max,2020-02-25 00:00:00,100.000000,82.819618,81.941295,693.526701
std,NaN,21.643791,18.992310,2.608969,95.901059

+ Save your cleaned dataset in a csv file using ``df_clean.to_csv``. Use the name ``temperature_clean.csv``.

In [87]:
df_clean.to_csv('temperature_clean.csv')

+ Save the cleanded data set in an Microsoft Excel format. Look at [pandas.DataFrame](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html) for the right function. Call the file ``temperature_clean.xlsx``.

In [88]:
# your code here
df_clean.to_excel('temperature_clean.xlsx')

+ Download the the newly created ``temperature_clean.xlsx`` file to your computer and open it up. There is no need to show something here. Just do it for your own education. If you are running the Jupyter notebook on your own computer, then there is nothing to do apart from finding the file. If you are working on Google Colab, see [this](https://stackoverflow.com/questions/48774285/how-to-download-file-created-in-colaboratory-workspace).

In [89]:
def colab2pdf():
  # @title Download Notebook in PDF Format{display-mode:'form'}
  !apt-get install -yqq --no-install-recommends librsvg2-bin>/dev/null;
  import contextlib,datetime,google,io,IPython,ipywidgets,json,locale,nbformat,os,pathlib,requests,urllib,warnings,werkzeug,yaml,re;locale.setlocale(locale.LC_ALL,'en_US.UTF-8');warnings.filterwarnings('ignore',category=nbformat.validator.MissingIDFieldWarning);
  %matplotlib inline
  def convert(b):
    try:
      s.value='🔄 Converting';b.disabled=True
      n=pathlib.Path(werkzeug.utils.secure_filename(urllib.parse.unquote(requests.get(f'http://{os.environ["COLAB_JUPYTER_IP"]}:{os.environ["KMP_TARGET_PORT"]}/api/sessions').json()[0]['name'])))
      p=pathlib.Path('/content/pdfs')/f'{datetime.datetime.utcnow().strftime("%Y%m%d_%H%M%S")}_{n.stem}';p.mkdir(parents=True,exist_ok=True);nb=nbformat.reads(json.dumps(google.colab._message.blocking_request('get_ipynb',timeout_sec=600)['ipynb']),as_version=4)
      u=[u for c in nb.cells if c.get('cell_type')=='markdown' for u in re.findall(r'!\[.*?\]\((https?://.*?)\)',c['source']) if requests.head(u,timeout=5).status_code!=200]
      if u:raise Exception(f"Bad Image URLs: {','.join(u)}")
      nb.cells=[cell for cell in nb.cells if '--Colab2PDF' not in cell.source]
      nb=nbformat.v4.new_notebook(cells=nb.cells or [nbformat.v4.new_code_cell('#')]);nbformat.validator.normalize(nb)
      nbformat.write(nb,(p/f'{n.stem}.ipynb').open('w',encoding='utf-8'))
      with (p/'config.yml').open('w', encoding='utf-8') as f: yaml.dump({'include-in-header':[{'text':r'\usepackage{fvextra}\DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaksymbolleft={},showspaces=false,showtabs=false,breaklines,breakanywhere,commandchars=\\\{\}}'}],'include-before-body':[{'text':r'\DefineVerbatimEnvironment{verbatim}{Verbatim}{breaksymbolleft={},showspaces=false,showtabs=false,breaklines}'}]},f)
      !quarto render {p}/{n.stem}.ipynb --metadata-file={p}/config.yml --to pdf -M latex-auto-install -M margin-top=1in -M margin-bottom=1in -M margin-left=1in -M margin-right=1in --quiet
      google.colab.files.download(str(p/f'{n.stem}.pdf'));s.value=f'✅ Downloaded: {n.stem}.pdf'
    except Exception as e:s.value=f'❌ {str(e)}'
    finally:b.disabled=False
  if not pathlib.Path('/usr/local/bin/quarto').exists():
    !wget -q 'https://quarto.org/download/latest/quarto-linux-amd64.deb' && dpkg -i quarto-linux-amd64.deb>/dev/null && quarto install tinytex --update-path --quiet && rm quarto-linux-amd64.deb
  b=ipywidgets.widgets.Button(description='⬇️ Download');s=ipywidgets.widgets.Label();b.on_click(lambda b:convert(b));IPython.display.display(ipywidgets.widgets.HBox([b,s]))
colab2pdf() # | Colab2PDF v1.6 | https://github.com/drengskapur/colab2pdf | GPL-3.0-or-later |

HBox(children=(Button(description='⬇️ Download', style=ButtonStyle()), Label(value='')))

/tmp/ipykernel_1414/41980980.py:10: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  p=pathlib.Path('/content/pdfs')/f'{datetime.datetime.utcnow().strftime("%Y%m%d_%H%M%S")}_{n.stem}';p.mkdir(parents=True,exist_ok=True);nb=nbformat.reads(json.dumps(google.colab._message.blocking_request('get_ipynb',timeout_sec=600)['ipynb']),as_version=4)